saayam-for-all/webapp

- src/common/components/Navbar/Navbar.jsx
- src/routes/routes.jsx
We created a new userpool last week, I used the hosted UI url in the handle login function.
> modified the cognito URL

- src/pages/Directors/Directors.jsx
- src/pages/LandingPage/components/Info.jsx
changes in Directors page
1. Remove the Name label
2. change role color to black
3. remove LinkedIn logo
4. put LinkedIn link as Name and change the color to blue
> updated directors page

- src/pages/Dashboard/Dashboard.jsx
Changed the button names in the dashboard.
> Changed button names

- src/common/components/Navbar/NavBar.css
- src/index.css
- src/pages/HelpRequest/HelpRequestForm.jsx
- src/routes/routes.jsx
changed the request form design and added cancel/submit button
> fix: change the request form interface

- src/pages/HelpRequest/HelpRequestForm.jsx
added a warning message at the top of the form
> add warning message in request form

- src/pages/Volunteer/newVolunteer.jsx
commented out the bootstrap style import line (need to rewrite the component using tailwind css)
> fix: comment out bootstrap import line

- src/common/components/DataTable/Table.jsx
- src/common/components/Pagination/Pagination.jsx
- src/pages/Dashboard/Dashboard.jsx
Included the rows per view, prev and next buttons, page numbers, and showing x-y pages in the pagination. Implemented filters for status and categories. Added sorting option in the creation date.
> Deepika dashboardtable

- src/common/components/Navbar/NavBar.css
- src/common/components/Navbar/Navbar.jsx
I have added icons on the Navbar from the react-icons library. The icons selected are the same as those on the mobile app to maintain consistency.
> Added NavBar Icons and styling

- src/common/components/Navbar/Navbar.jsx
Updated Donate icon based on UX design.
> Updated Donate Icon

- src/pages/Volunteer/steps/VolunteerCourse.jsx
- Added functionality for users to upload files from either their device, Google Drive, or Dropbox.
- Implemented validation for file size (max 2MB) and file types (JPEG, JPG, PDF).
- Added preview for locally uploaded files.
> Implemented VPW - Step 2 - FE

- src/pages/Volunteer/PromoteToVolunteer.jsx
- src/pages/Volunteer/steps/Availability.jsx
The volunteer promotion wizard has been structured into four steps, with the fourth step specifically dedicated to collecting volunteer's availability.
**Emergency Contact Checkbox:**
Added a checkbox allowing volunteers to indicate whether they can be contacted in case of emergencies or critical situations.
**Time Zone Selection:**
Introduced a dropdown box that allows volunteers to select their time zone, ensuring that availability times are accurately recorded and interpreted.
**Availability Time Inputs:**
Volunteers can input their available days, start times, and end times. These inputs are structured as a list, allowing users to add or delete time slots as needed.
> Implemented step-4 of volunteer promotion wizard

- src/pages/Volunteer/steps/Availability.jsx
Removed timezone component in step-t of volunteer promotion wizard.
Added default day(Everyday) and times(12:00 AM) for availability times for user convenience.
Moved the calamity checkbox to bottom.
> removed timezone component in step-4 of vpw

- package-lock.json
- package.json
- src/pages/Volunteer/PromoteToVolunteer.jsx
- src/pages/Volunteer/steps/PersonalInfo.jsx
- src/pages/Volunteer/steps/Skills.jsx
For now, the category values are hard coded and a hierarchical checkbox list is implemented for volunteer skills page. If any checkbox has subcategories associated with it and if it's checked, only then the sub-categories checkbox list is displayed. The implementation supports multiple levels of sub-categories.
> Implemented step-3 of volunteer promotion wizard

- src/main.jsx
removed unwanted css imports in main.jsx file
> fix: remove unwanted imports in main.jsx

- src/pages/Profile/ChangePassword.jsx
- src/pages/Profile/OrganizationDetails.jsx
- src/pages/Profile/PersonalInformation.jsx
- src/pages/Profile/Profile.jsx
- src/pages/Profile/YourProfile.jsx
Implemented an unsaved changes warning that triggers if the user edits any field and attempts to navigate away without saving. This helps prevent accidental loss of user input.
> Add Unsaved Changes Warning Across All Profile Tabs

- src/Layout/Layout.jsx
- src/pages/Contact/Contact.jsx
- src/redux/features/authentication/authActions.js
- src/routes/routes.jsx
fix to redirect to dashboard page immediately after successful login
stored the user properties coming from cognito in redux global state
> Gourav refactor webapp

- src/pages/RequestDetails/HelpingVolunteers.jsx
- src/pages/RequestDetails/RequestDetails.jsx
- src/pages/RequestDetails/RequestDetailsSidebar.jsx
Created the helping volunteers component for the request details page.
> Added the helping volunteers with dummy data

- src/pages/HelpRequest/HelpRequestForm.jsx
- src/pages/RequestDetails/RequestDescription.jsx
- closed the form if it's editing the help request form
- redirect back to dashboard if it's creating the help request form 
- fixed some responsive styles for the description on the request detail page
> added cancel button functionality on help request form

- src/pages/RequestDetails/Comments.jsx
- src/pages/RequestDetails/CommentsSection.jsx
Made changes to comment section UI to make it look like mockup screen
> Comment Section UI changes of Request detail page

- src/pages/RequestDetails/HelpingVolunteers.jsx
as mentioned in the previous meeting for adding the already assigned volunteers is now added.
> added the voluteers assigned

- src/pages/RequestDetails/CommentsSection.jsx
comment section updates after demo
> comment section updates after demo

- .github/workflows/CICDPipeline.yaml
Merge main backwards into dev to propagate changes made directly in main
> Merge main backwards

- .github/workflows/CICDPipeline.yaml
- LICENSE
Propagate changes up from dev to test
> Merge dev into test

- package-lock.json
- src/pages/Profile/YourProfile.jsx
Reordered the fields of Your profile tab to align with the sign-up page and changed the phone number and country name logic.
> Refactor Your Profile Tab

- .babelrc
- .eslintrc.cjs
- .github/workflows/CICDPipeline.yaml
- jest.config.cjs
- package-lock.json
- package.json
- src/common/components/Footer/footer.test.js
Add a basic unit test so that unit tests can be used in CI/CD.
This change also updates CI/CD to trigger for PRs to dev branch, not just main.
> Add a basic unit test

- src/common/components/Pagination/Pagination.jsx
- src/pages/Dashboard/Dashboard.jsx
- src/pages/HelpRequest/HelpRequestForm.jsx
- src/pages/RequestDetails/RequestDescription.jsx
- src/redux/store.js
- src/services/requestApi.js
- fixed styles & UI for the description section on request detail page
- added fetching existing data on request form
> Wing description request detail

- package-lock.json
- package.json
- src/pages/Volunteer/steps/Availability.jsx
- src/pages/Volunteer/steps/TermsConditions.jsx
I've made changes to both the issues: Enabled terms checkbox for issue 231 and fixed headers for issue 187. For the reference, I've added the screenshots. Please review the changes made.
> Enabled terms checkbox for issue 231 and fixed headers for issue 187 

- .env
- src/pages/Dashboard/Dashboard.jsx
- src/pages/RequestDetails/RequestDescription.jsx
- src/pages/RequestDetails/VoluntaryOrganizations.jsx
- src/pages/Volunteer/PromoteToVolunteer.jsx
- src/pages/Volunteer/steps/Skills.jsx
- src/services/api.js
- src/services/endpoints.json
- src/services/requestServices.js
- src/services/volunteerServices.js
- tests/pages/PromoteToVolunteer.test.js
- tests/pages/requestDetails/RequestDetails.test.js
#248 apply filters on deselecting all filters and selecting individual filters in requests and volunteers grid. 
#259 get volunteer skills and organizations from API
> #249 make separate api calls for each requests.

- src/pages/Dashboard/Dashboard.jsx
- src/pages/HelpRequest/HelpRequestForm.jsx
- Hid other requests on dashboard
- Hid "for self" dropdown when creating a new request
> Remove non mvp features

- src/pages/Auth/VerifyOtp.jsx
Made changes in handleChange & handleKeyDown functions to edit the OTP after received in src>pages>Auth>VerifyOTP.jsx.
> User can't edit verification code #270

- package-lock.json
- src/common/components/DataTable/Table.jsx
- src/common/components/Pagination/Pagination.jsx
- src/pages/Auth/Login.css
- src/pages/Auth/Login.jsx
- src/pages/Auth/Signup.jsx
- src/pages/Auth/VerifyOtp.jsx
- src/pages/Dashboard/Dashboard.jsx
- src/pages/HelpRequest/HelpRequestForm.jsx
- src/pages/RequestDetails/RequestDescription.jsx
- When focusing on password/confirm-password input in the login/sign-up screen, a border would appear on the password input that would shift all the elements. Changed it so that the border would no longer shift other elements.
- In Microsoft Edge/IE a duplicate "see password" eye would appear on the password inputs. Removed this duplicate eye.
- When verifying OTP, the verification button would disappear on hover since no background color was set. Added a gray background color on hover to prevent it from disappearing. 
- Added phone and video icons on the request details page
- On the create help request page you couldn't click away from request category without selecting a category. Fixed this so that you can click away
- Hovering on page numbers in the dashboard would make them …
> Fixed a variety of bugs

- src/pages/Dashboard/Dashboard.jsx
Reverts saayam-for-all/webapp#286
> Revert "Heet on hover text invisible"

- src/pages/Auth/Signup.jsx
>  Allow space between words in First name, Last name fields of the Sign Up page #292

- src/pages/Auth/Signup.jsx
Added a pop-up on the right side of the password test box to show password validations to the user
> Added pop-up to show password validations to the user

- src/common/components/Navbar/Navbar.jsx
- src/pages/Auth/Login.jsx
- Also prevented the user from going to the login page if they were already logged in. Now they will be redirected to the dashboard page
> Fixed bug where profile drawer was visible upon login

- src/common/components/Navbar/NavBar.css
- src/common/components/Navbar/Navbar.jsx
Issue #288 Added Responsiveness for the Nav Bar in terms of mobile and other views. 
Resolved the Issues regarding the About US page functionality .
> Issue 288: Navbar responsive fixes

- src/pages/Auth/Signup.jsx
fixed signup page not loading issue.
> Signup page was not loading and giving error.

- src/redux/features/help_request/requestActions.js
Added Counseling support with sub categories.
> Updated Dropdown

- src/common/components/Footer/Footer.jsx
- src/common/components/Footer/footer.test.js
- tests/pages/common/Components/footer.test.js
changed footer from saayam to "saayam for all".
> changes made

- src/pages/Profile/ChangePassword.jsx
- src/pages/Profile/OrganizationDetails.jsx
- src/pages/Profile/PersonalInformation.jsx
- src/pages/Profile/YourProfile.jsx
In the profile tabs—Your Profile, Personal Information, Change Password, and Organization Details—when clicking "Edit," the fields currently change to a grey color. now i changed them into white colour .
> Change the colour of editable fields in profile tabs

- src/pages/RequestDetails/RequestDescription.jsx
- src/pages/RequestDetails/RequestDetails.jsx
Moved the volunteer details below the request header
> worked on moving the volunteer details below the request header

- src/hooks/useDebounce.jsx
- src/pages/HelpRequest/HelpRequestForm.jsx
- src/services/endpoints.json
- src/services/requestServices.js
#262 - Integrated predict categories api in help request form
> Integrated predict categories api in help request form 

- src/pages/Auth/Signup.jsx
• Implemented dynamic password validation popup with absolute positioning and clamp(200px,25vw,300px) width, positioned to the right using left-full
• Added conditional rendering logic ((showPasswordValidation && !allRequirementsMet) || errors.password) for validation popup visibility 
• Integrated real-time password requirement checks using regex patterns with visual feedback (green/red status indicators) 
• Implemented form state management using useState hooks for validation states, error handling, and password visibility toggles 
• Added CSS classes for input states using template literals for dynamic border styling (border-red-500, border-black, border-gray-300)
> Enhanced Password Validation UI with Real-time Visual Feedback

- package-lock.json
- src/pages/Profile/PersonalInformation.jsx
Changed Date of Birth format based on the country
> DOB localisation

- src/pages/Profile/OrganizationDetails.jsx
Merging Email Validation, Phone Number ( 10 Digits ) , URL with https://, http:// in OriganizationDetails.jsx page.
> Test manish malepati 415

- src/pages/Dashboard/Dashboard.jsx
Removed existing 'Administrate' link and Added Administrate button to open dropdown with values SuperAdmin Dashboard, Admin Dashboard, Steward Dashboard, Volunteer Dashboard, Beneficiary Dashboard
> Create a dropdown on dashboard #419

- src/pages/HelpRequest/HelpRequestForm.jsx
Added Lead Volunteer input field on edit request page
> add volunteer lead name on edit request page

- src/pages/Dashboard/Dashboard.jsx
Updated from 'SuperAdmin Dashboard' to 'Super Admin Dashboard'.
> Fix Dashboard dropdown #476

- src/pages/Profile/Skills.jsx
Coded and Tested.
Merging for Issue #459.
Skills to be listed as bullet points using Mui Lists when not in Edit Mode in Skills.jsx.
> Showing Selected Skills in Bullet Points using Mui

- src/pages/Profile/PersonalInformation.jsx
Made changes as per description of Task, please check and verify.
> 392 webapp

- src/pages/Profile/OrganizationDetails.jsx
Made the necessary changes to fix the issue
> Unnecesary popup fix on Organization details page

- __mocks__/fileTransformer.cjs
- __mocks__/fileTransformer.js
- jest.config.js
- package-lock.json
- src/pages/Donate/Donate.jsx
- src/pages/Donate/__snapshots__/donate.test.js.snap
- src/pages/Donate/donate.test.js
- src/pages/HelpRequest/HelpRequestForm.jsx
- src/pages/Profile/Profile.jsx
- src/pages/Volunteer/PromoteToVolunteer.jsx
added back button in 4 required files.
> back button added

- src/Layout/Layout.jsx
- src/common/components/Navbar/Navbar.jsx
- src/common/components/Navbar/__snapshots__/navbar.test.js.snap
- src/common/components/Navbar/navbar.test.js
- src/context/NotificationContext.jsx
- src/pages/Notifications/Notifications.jsx
- src/routes/routes.jsx
- src/services/endpoints.json
- src/services/requestServices.js
- utils/test-utils.jsx
Creation of notification page by adding all the functionality.
> Notifications Page Creation

- src/pages/Sitemap/Sitemap.jsx
Added the hyperlinks to all of them
> Added hyperlinks

- src/pages/Profile/PersonalInformation.jsx
validations for profile personal information page
> added validations

- src/pages/Auth/Signup.jsx
As part of MVP 0.5, limited signup country selection to United States to align with initial release requirements.
> Restrict country field to United States for 0.5 MVP release

- src/App.jsx
- src/common/components/Navbar/Navbar.jsx
- src/common/components/Navbar/__snapshots__/navbar.test.js.snap
- src/index.css
- src/pages/About Us/OurMission/JoinCTA.jsx
- src/pages/About Us/OurMission/Mission.jsx
- src/pages/About Us/OurMission/MissionHero.jsx
- src/pages/About Us/OurMission/Vision.jsx
- src/pages/Sitemap/Sitemap.css
- tailwind.config.js
1. Modified the global CSS to set "Roboto", sans-serif as the default font-family.
2. Ensured Roboto is properly imported via Google Fonts for consistent rendering across browsers.
> Update global font to Roboto

- package-lock.json
- package.json
- src/pages/HelpRequest/HelpRequestForm.jsx
Added the tooltips for dropdowns on Create Request Page
> Added Tooltips

- src/common/i18n/locales/en_US.json
- src/pages/Donate/Donate.css
- src/pages/Donate/Donate.jsx
- src/pages/Donate/__snapshots__/donate.test.js.snap
-Removed the QR code section from the donation page UI and code.
-Added new donation buttons for Charity Navigator and Benevity, each with their respective URLs. 
-Implemented and styled the .donate-button-charity and .donate-button-benevity CSS classes to match the appearance of the other donation buttons. 
-Ensured all donation buttons (PayPal, RazorPay, Stripe, Charity Navigator, Benevity) are present, styled consistently and open their links in a new tab.
> -Removed the QR code section from the donation page UI and code.

- src/pages/HelpRequest/HelpRequestForm.jsx
#Update the inline message in the dashboard page.
> #427 Story

- src/pages/RequestDetails/RequestDetails.jsx
Fix All caps text on Request details page #559
> task 559 capitalize

- src/pages/Donate/Donate.jsx
- src/pages/Donate/__snapshots__/donate.test.js.snap
- src/pages/RequestDetails/OrganizationDetails.jsx
- src/pages/RequestDetails/RequestDetails.jsx
- src/pages/RequestDetails/VoluntaryOrganizations.jsx
Added back buttons to the following pages: RequestDetails page, OrganizationDetails page, VoluntaryOrganizations page, Donate page.
> Add back buttons to RequestDetails, OrganizationDetails, VoluntaryOrg and Donate page

- src/common/components/Navbar/Navbar.jsx
Corrected the routing for Our Collaborators page on mobile devices
> Fix: Corrected routing for Our Collaborators page on mobile devices

- src/pages/Donate/Donate.jsx
- src/pages/Donate/__snapshots__/donate.test.js.snap
Removed the back button from the Donate page as instructed
> Remove back button from Donate page

- src/pages/Profile/Availability.jsx
- src/pages/Profile/Profile.jsx
- src/pages/Profile/Sidebar.jsx
Added a new "Availability" tab to the User Profile page where users can view, edit, and update their available time slots for volunteering.
> Add Availability tab to user profile for volunteer time slots

- src/pages/Directors/Directors.jsx
- src/pages/Directors/__snapshots__/directors.test.js.snap
Changing the roles from advisor to director
> Role changes

- src/common/components/Navbar/Navbar.jsx
- src/common/components/Navbar/__snapshots__/navbar.test.js.snap
- src/pages/HelpRequest/HelpRequestForm.jsx
> 262 Bug - Help Request Form Changes

- src/pages/HelpRequest/HelpRequestForm.jsx
#262 
Added fix for showing errors for profanity in help request form
> added popup for error msg for profanity

- package-lock.json
- src/pages/HelpRequest/HelpRequestForm.jsx
Fixed the overlaying issue of the dropdown field of the request category field on the create help request page
> Fixed the overlaying issue of the dropdown field

- src/pages/Profile/Preferences.jsx
- src/pages/Profile/Profile.jsx
- src/pages/Profile/Sidebar.jsx
Created new Preference Tab in Profile section
> Task 478 : Preference Tab

- src/common/components/DataTable/Table.jsx
- src/common/components/DataTable/__snapshots__/table.test.js.snap
- src/common/components/Pagination/Pagination.jsx
- src/common/components/Pagination/__snapshots__/pagination.test.js.snap
- src/common/components/Wizard/Stepper.jsx
- src/pages/About Us/OurMission/JoinCTA.jsx
- src/pages/HelpRequest/HelpRequestForm.jsx
- src/pages/LandingPage/LandingPage.jsx
- src/pages/LandingPage/__snapshots__/landing-page.test.js.snap
- src/pages/LandingPage/components/Carousel.jsx
- src/pages/Notifications/Notifications.jsx
- src/pages/Profile/Sidebar.jsx
- src/pages/RequestDetails/Comments.jsx
- src/pages/RequestDetails/HelpingVolunteers.jsx
- src/pages/Volunteer/Stepper.jsx
> Changing the color

- src/common/components/Footer/Footer.jsx
- src/common/components/Footer/__snapshots__/footer.test.js.snap
> Updated bottom nav bar links

- src/pages/Auth/VerifyOtp.jsx
- src/pages/Profile/YourProfile.jsx
- src/pages/Profile/__snapshots__/your-profile.test.js.snap
- src/pages/Profile/your-profile.test.js
Implemented email change verification in the profile update flow by adding a VerifyEmailChange page for OTP entry, using AWS Amplify to handle email updates, confirmation codes, and resend support. The flow ensures users verify their new email before completing profile updates.
> Email Verification for profile update

- src/pages/Directors/Directors.jsx
- src/pages/Directors/__snapshots__/directors.test.js.snap
- src/pages/Directors/data/executiveTeam.js
1)Fixed the linked-in links 
2)Fixed the alignment of the directors and their roles
> Fixed team page

- src/pages/About Us/OurMission/MissionHero.jsx
> Our Mission

- src/pages/Contact/ContactUs.jsx
> Added setup for contact us form

- src/pages/About Us/OurMission/Mission.jsx
- src/pages/About Us/OurMission/MissionHero.jsx
- src/pages/About Us/OurMission/Vision.jsx
#463 Changes in Our Vision(text spaces & images left top, left bottom & right top and right bottom circular curves, Our Values text + boxes ( text and spaces ), Our Mission text & Image size alignment.
> #463 Our Mission Changes

- src/common/components/Footer/Footer.jsx
- src/common/components/Footer/__snapshots__/footer.test.js.snap
- src/pages/PrivacyPolicy/PrivacyPolicy.css
- src/pages/PrivacyPolicy/PrivacyPolicy.jsx
- src/routes/routes.jsx
Privacy Policy page has been created and linked with the website
> Privacy Policy page

- src/common/i18n/locales/hi_IN.json
#703 - Completed with Hindi translation for 0.5 MVP
Updated Donation page:
> feat: Add donation-related translations to Hindi localization

- README.md
Issue #743 The README file now contains the correct repository link and updated information on setting up the environment for webapp.
> Fixed the readme document with the correct repository

- src/pages/Directors/Directors.jsx
- src/pages/Directors/__snapshots__/directors.test.js.snap
aligned directors same as executives
> fixed alignment in directors.jsx

- src/pages/LandingPage/LandingPage.jsx
Fixed - Navigation to dashboard post login
> Fixed - Navigation to dashboard post login

- index.html
Issue #719 Added the required scripts
> added google tag manager scripts

- src/pages/About Us/OurMission/JoinCTA.jsx
issue #776 This issue is now complete
> contact us page is now connected

- src/pages/Donate/Donate.css
-Updated the donate page and fixed the background image for the mobile screens.
> Updated the donate page for the mobile screens

- src/pages/Auth/Signup.jsx
> TOS link open in the same tab

- src/pages/Volunteer/steps/Availability.jsx
Volunteer wizard step 4 shows validation error before user even enters value in the field #835
Fixed and added validation.
> Fixed Validation error on Volunteer wizard

- src/common/i18n/utils.js
Reverting the fix for console en_IN/en_GB related bug #873
> Reverting the fix for console bug

- src/pages/HelpRequest/HelpRequestForm.jsx
I updated the “For Self” dropdown to make it fully interactive by removing the disabled attribute. I also added a “No” option alongside the existing “Yes” option, while keeping “Yes” as the default selection using defaultValue="yes".
> Rudra add no to For Self dropdown in Create Help Request

- src/pages/Collaborators/Collaborators.jsx
Fixed the font size to match the rest of the pages.
> fix: standardize Collaborators page text sizing for consistency

- src/common/i18n/locales/en/categories.json
- src/common/i18n/locales/es/categories.json
- src/common/i18n/locales/fr/categories.json
- src/pages/HelpRequest/HelpRequestForm.jsx
- Updated categories.json files (en, es, fr) to use exact API keys like FOOD_AND_ESSENTIALS_SUPPORT, GENERAL_CATEGORY, etc.
- Updated HelpRequestForm.jsx mapping to direct 1:1 mapping since API keys now match i18n keys exactly
- Added all subcategories with exact API names (GROCERY_SHOPPING_AND_DELIVERY, BORROW_CLOTHES, etc.)
- LABEL fields remain user-friendly (Food & Essentials, Clothing Support, etc.)
> Update categories to use exact API keys from Rashmi's documentation

- src/pages/ForgotPasswordPage/ForgotPasswordPage.jsx
Added Back Button in Forgot Password Page.
> added back button to forgot password page

- src/pages/Dashboard/Dashboard.jsx
- src/pages/Profile/PersonalInformation.jsx
> block create request & become a volunteer buttons in dashboard until address is filled in profile section

- src/pages/Dashboard/Dashboard.jsx
- src/pages/Profile/PersonalInformation.jsx
- src/pages/Profile/Profile.jsx
> redirect create request & become a volunteer buttons in dashboard to personal information tab in profile section if address is not filled

- src/pages/LandingPage/LandingPage.jsx
- src/pages/LandingPage/__snapshots__/landing-page.test.js.snap
Centerlized the Landing Page text, when it changed language to telugu.
> Landing page text alignment

- src/pages/ForgotPasswordPage/ForgotPasswordPage.jsx
> back button changed for consistency

- src/pages/Volunteer/PromoteToVolunteer.jsx
- src/pages/Volunteer/StepperControl.jsx
- src/pages/Volunteer/steps/VolunteerCourse.jsx
Removed Upload Button and also disabled next button unless user uploads a valid file.
> Volunteer Wizard Step2 Changes

- src/pages/Notifications/Notifications.jsx
> Added pagination functionality in notifications page

- src/Layout/Layout.jsx
- src/Layout/__snapshots__/layout.test.js.snap
- src/pages/Profile/PersonalInformation.jsx
- src/pages/Profile/Profile.jsx
- src/pages/Profile/Sidebar.jsx
This is a partial fix commit for the main issue #977 
Here are the partial fixes:
1. Implemented the sliding side navigation bar for the /profile page on mobile devices.
2. Enhanced the 'Year' selection dropdown in the 'Personal Info' tab to include month/year dropdowns, scrollable selection, and show 100 years for easy access (using react-datepicker properties).
3. Updated the mobile layout for ads sections to ensure proper stacking.
Note:
- This Pull Request represents a partial fix for the main objective of issue #977.
- Do not close this issue until all items in the original scope are completed.
- Upon successful merge, please leave a comment under issue #977 detailing what was accomplished in this merge and clearly listing the remaining, pending tasks.
> Partially addresses #977 Fix(Mobile): Implement profile sidebar navigation..
